# Generated by Django 3.2.4 on 2021-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default='', max_length=20)),
                ('decc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
