# Generated by Django 3.2.4 on 2021-07-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdade',
            new_name='OrderUpdate',
        ),
    ]
